image: node:19.2.0-alpine

cache: &global_cache
  key:
    files:
      - schemcat/pnpm-lock.yaml
  paths:
    - schemcat/node_modules/
    - schemcat/.pnpm-store/
  policy: pull

schemcat-install:
  stage: .pre
  cache:
    <<: *global_cache
    policy: pull-push
  before_script:
    - apk update && apk add curl
    - curl -fsSL "https://github.com/pnpm/pnpm/releases/download/v7.15.0/pnpm-linuxstatic-x64" -o /bin/pnpm; chmod +x /bin/pnpm;
    - pnpm config set store-dir .pnpm-store
    - cd schemcat
  script:
    - pnpm install

schemcat-build:
  stage: build
  cache:
    <<: *global_cache
  before_script:
    - apk update && apk add curl
    - curl -fsSL "https://github.com/pnpm/pnpm/releases/download/v7.15.0/pnpm-linuxstatic-x64" -o /bin/pnpm; chmod +x /bin/pnpm;
    - pnpm config set store-dir .pnpm-store
    - cd schemcat
  script:
    - pnpm build
  artifacts:
    paths:
      - schemcat/dist/
    expire_in: 7 days

schemcat-test:
  stage: test
  cache:
    <<: *global_cache
  before_script:
    - apk update && apk add curl
    - curl -fsSL "https://github.com/pnpm/pnpm/releases/download/v7.15.0/pnpm-linuxstatic-x64" -o /bin/pnpm; chmod +x /bin/pnpm;
    - pnpm config set store-dir .pnpm-store
    - cd schemcat
  script:
    - pnpm test

schemcat-gh-pages:
  stage: deploy
  cache:
    <<: *global_cache
  before_script:
    - apk update && apk add curl openssl ca-certificates git
    - curl -fsSL "https://github.com/pnpm/pnpm/releases/download/v7.15.0/pnpm-linuxstatic-x64" -o /bin/pnpm; chmod +x /bin/pnpm;
    - pnpm config set store-dir .pnpm-store
    - cd schemcat
  script:
    - pnpm build
    - git clone --depth 1 https://sorashi:$GITHUB_ACCESS_TOKEN@github.com/sorashi/schemcat.git
    - mkdir schemcat.new
    # clean working dir, preserve .git
    - cp -a schemcat/.git schemcat.new/.git
    - cp -a dist/* schemcat.new/
    - cd schemcat.new
    - touch .nojekyll
    - git config user.email prazak.dennis@gmail.com
    - git config user.name "Dennis Prazak"
    - git add -A
    # commit only if there are changes
    - git diff-index --quiet HEAD || git commit -m "$CI_SERVER_NAME $CI_PIPELINE_ID"
    - git push
  # deploy to production when a tag is pushed 
  only: [ tags ]
  # ignore all branches except the default branch (i.e. must tag master)
  except: [ branches ]

bp-build:
  image: aergus/latex:latest
  stage: build
  before_script:
    - cd text/cs
  script:
    - make all
  artifacts:
    paths:
      - text/cs/prace.pdf
      - text/cs/abstract.pdf
    expire_in: 1 week

bp-verify:
  image: ghcr.io/mff-cuni-cz/cuni-thesis-validator:latest
  script:
    - cd text/cs
    - verify prace.pdf | grep 'isCompliant="true"'
    - verify abstract.pdf | grep 'isCompliant="true"'
