env:
    browser: true
    es2021: true
extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:import/recommended
    - plugin:import/typescript
    - plugin:@typescript-eslint/recommended
    - plugin:react/jsx-runtime
overrides: []
settings:
    react:
        version: detect
    import/resolver:
        node:
            paths: [src]
            extensions: [.js, .jsx, .ts, .tsx]
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - "@typescript-eslint"
rules:
    indent:
        - error
        - 4
    quotes:
        - error
        - double
    semi:
        - error
        - never
