env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:react/jsx-runtime
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: []
settings:
  react:
    version: detect
  import/resolver:
    node:
      paths: [src]
      extensions: [.js, .jsx, .ts, .tsx]
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - '@typescript-eslint'
  - react
rules:
  '@typescript-eslint/no-empty-function':
    - error
    - allow:
        - private-constructors
